package com.comoelagua.android.braille.model.daos;

import com.comoelagua.android.braille.model.beans.Word;

import java.util.ArrayList;

public class WordsDao implements CrudDao {

    public WordsDao() {
    }

    @Override
    public Object create(Object obj) {
        return null;
    }

    @Override
    public Object update(Object obj) {
        return null;
    }

    @Override
    public <T> ArrayList<T> read(ArrayList<Criteria> criteriaList) {
        boolean random = false;
        int length = 0;
        for(Criteria criteria : criteriaList) {
            if (criteria.getParameter() == "random") {
                random = true;
            }
            if (criteria.getParameter() == "length") {
                length = Integer.parseInt( criteria.getValue() );
            }
        }
        if (random && length > 0) {
            ArrayList<T> wordsList = (ArrayList<T>) readRandom(length);
            return wordsList;
        }
        return null;
    }

    @Override
    public boolean delete(Object object) {
        return false;
    }

    public ArrayList<Word> readRandom(int length) {
        ArrayList<Word> wordsList = readAll();
        ArrayList<Word> shortWordsList = new ArrayList<Word>();
        for(int i = 0; i < length; i++) {
            int randomNum = 1 + (int) (Math.random() * wordsList.size());
            shortWordsList.add( wordsList.get(randomNum) );
        }
        return shortWordsList;
    }

    public ArrayList<Word> readAll() {
        ArrayList wordsList = new ArrayList<Word>();
        wordsList.add( new Word(1, "de") );
        wordsList.add( new Word(2, "la") );
        wordsList.add( new Word(3, "que") );
        wordsList.add( new Word(4, "el") );
        wordsList.add( new Word(5, "en") );
        wordsList.add( new Word(6, "y") );
        wordsList.add( new Word(7, "a") );
        wordsList.add( new Word(8, "los") );
        wordsList.add( new Word(9, "se") );
        wordsList.add( new Word(10, "del") );
        wordsList.add( new Word(11, "las") );
        wordsList.add( new Word(12, "un") );
        wordsList.add( new Word(13, "por") );
        wordsList.add( new Word(14, "con") );
        wordsList.add( new Word(15, "no") );
        wordsList.add( new Word(16, "una") );
        wordsList.add( new Word(17, "su") );
        wordsList.add( new Word(18, "para") );
        wordsList.add( new Word(19, "es") );
        wordsList.add( new Word(20, "al") );
        wordsList.add( new Word(21, "lo") );
        wordsList.add( new Word(22, "como") );
        wordsList.add( new Word(23, "más") );
        wordsList.add( new Word(24, "o") );
        wordsList.add( new Word(25, "pero") );
        wordsList.add( new Word(26, "sus") );
        wordsList.add( new Word(27, "le") );
        wordsList.add( new Word(28, "ha") );
        wordsList.add( new Word(29, "me") );
        wordsList.add( new Word(30, "si") );
        wordsList.add( new Word(31, "sin") );
        wordsList.add( new Word(32, "sobre") );
        wordsList.add( new Word(33, "este") );
        wordsList.add( new Word(34, "ya") );
        wordsList.add( new Word(35, "entre") );
        wordsList.add( new Word(36, "cuando") );
        wordsList.add( new Word(37, "todo") );
        wordsList.add( new Word(38, "esta") );
        wordsList.add( new Word(39, "ser") );
        wordsList.add( new Word(40, "son") );
        wordsList.add( new Word(41, "dos") );
        wordsList.add( new Word(42, "también") );
        wordsList.add( new Word(43, "fue") );
        wordsList.add( new Word(44, "había") );
        wordsList.add( new Word(45, "era") );
        wordsList.add( new Word(46, "muy") );
        wordsList.add( new Word(47, "años") );
        wordsList.add( new Word(48, "hasta") );
        wordsList.add( new Word(49, "desde") );
        wordsList.add( new Word(50, "está") );
        wordsList.add( new Word(51, "mi") );
        wordsList.add( new Word(52, "porque") );
        wordsList.add( new Word(53, "qué") );
        wordsList.add( new Word(54, "sólo") );
        wordsList.add( new Word(55, "han") );
        wordsList.add( new Word(56, "yo") );
        wordsList.add( new Word(57, "hay") );
        wordsList.add( new Word(58, "vez") );
        wordsList.add( new Word(59, "puede") );
        wordsList.add( new Word(60, "todos") );
        wordsList.add( new Word(61, "así") );
        wordsList.add( new Word(62, "nos") );
        wordsList.add( new Word(63, "ni") );
        wordsList.add( new Word(64, "parte") );
        wordsList.add( new Word(65, "tiene") );
        wordsList.add( new Word(66, "él") );
        wordsList.add( new Word(67, "uno") );
        wordsList.add( new Word(68, "donde") );
        wordsList.add( new Word(69, "bien") );
        wordsList.add( new Word(70, "tiempo") );
        wordsList.add( new Word(71, "mismo") );
        wordsList.add( new Word(72, "ese") );
        wordsList.add( new Word(73, "ahora") );
        wordsList.add( new Word(74, "cada") );
        wordsList.add( new Word(75, "elefante") );
        wordsList.add( new Word(76, "vida") );
        wordsList.add( new Word(77, "otro") );
        wordsList.add( new Word(78, "después") );
        wordsList.add( new Word(79, "te") );
        wordsList.add( new Word(80, "otros") );
        wordsList.add( new Word(81, "aunque") );
        wordsList.add( new Word(82, "esa") );
        wordsList.add( new Word(83, "eso") );
        wordsList.add( new Word(84, "hace") );
        wordsList.add( new Word(85, "otra") );
        wordsList.add( new Word(86, "gobierno") );
        wordsList.add( new Word(87, "tan") );
        wordsList.add( new Word(88, "durante") );
        wordsList.add( new Word(89, "siempre") );
        wordsList.add( new Word(90, "día") );
        wordsList.add( new Word(91, "tanto") );
        wordsList.add( new Word(92, "ella") );
        wordsList.add( new Word(93, "tres") );
        wordsList.add( new Word(94, "sí") );
        wordsList.add( new Word(95, "dijo") );
        wordsList.add( new Word(96, "sido") );
        wordsList.add( new Word(97, "gran") );
        wordsList.add( new Word(98, "país") );
        wordsList.add( new Word(99, "según") );
        wordsList.add( new Word(100, "menos") );
        wordsList.add( new Word(101, "mundo") );
        wordsList.add( new Word(102, "año") );
        wordsList.add( new Word(103, "antes") );
        wordsList.add( new Word(104, "estado") );
        wordsList.add( new Word(105, "contra") );
        wordsList.add( new Word(106, "sino") );
        wordsList.add( new Word(107, "forma") );
        wordsList.add( new Word(108, "caso") );
        wordsList.add( new Word(109, "nada") );
        wordsList.add( new Word(110, "hacer") );
        wordsList.add( new Word(111, "general") );
        wordsList.add( new Word(112, "estaba") );
        wordsList.add( new Word(113, "poco") );
        wordsList.add( new Word(114, "estos") );
        wordsList.add( new Word(115, "presidente") );
        wordsList.add( new Word(116, "mayor") );
        wordsList.add( new Word(117, "ante") );
        wordsList.add( new Word(118, "unos") );
        wordsList.add( new Word(119, "les") );
        wordsList.add( new Word(120, "algo") );
        wordsList.add( new Word(121, "hacia") );
        wordsList.add( new Word(122, "casa") );
        wordsList.add( new Word(123, "ellos") );
        wordsList.add( new Word(124, "ayer") );
        wordsList.add( new Word(125, "hecho") );
        wordsList.add( new Word(126, "primera") );
        wordsList.add( new Word(127, "mucho") );
        wordsList.add( new Word(128, "mientras") );
        wordsList.add( new Word(129, "además") );
        wordsList.add( new Word(130, "quien") );
        wordsList.add( new Word(131, "momento") );
        wordsList.add( new Word(132, "millones") );
        wordsList.add( new Word(133, "esto") );
        wordsList.add( new Word(134, "españa") );
        wordsList.add( new Word(135, "hombre") );
        wordsList.add( new Word(136, "están") );
        wordsList.add( new Word(137, "pues") );
        wordsList.add( new Word(138, "hoy") );
        wordsList.add( new Word(139, "lugar") );
        wordsList.add( new Word(140, "madrid") );
        wordsList.add( new Word(141, "nacional") );
        wordsList.add( new Word(142, "trabajo") );
        wordsList.add( new Word(143, "otras") );
        wordsList.add( new Word(144, "mejor") );
        wordsList.add( new Word(145, "nuevo") );
        wordsList.add( new Word(146, "decir") );
        wordsList.add( new Word(147, "algunos") );
        wordsList.add( new Word(148, "entonces") );
        wordsList.add( new Word(149, "todas") );
        wordsList.add( new Word(150, "días") );
        wordsList.add( new Word(151, "debe") );
        wordsList.add( new Word(152, "política") );
        wordsList.add( new Word(153, "cómo") );
        wordsList.add( new Word(154, "casi") );
        wordsList.add( new Word(155, "toda") );
        wordsList.add( new Word(156, "tal") );
        wordsList.add( new Word(157, "luego") );
        wordsList.add( new Word(158, "pasado") );
        wordsList.add( new Word(159, "primer") );
        wordsList.add( new Word(160, "medio") );
        wordsList.add( new Word(161, "va") );
        wordsList.add( new Word(162, "estas") );
        wordsList.add( new Word(163, "sea") );
        wordsList.add( new Word(164, "tenía") );
        wordsList.add( new Word(165, "nunca") );
        wordsList.add( new Word(166, "poder") );
        wordsList.add( new Word(167, "aquí") );
        wordsList.add( new Word(168, "ver") );
        wordsList.add( new Word(169, "veces") );
        wordsList.add( new Word(170, "embargo") );
        wordsList.add( new Word(171, "partido") );
        wordsList.add( new Word(172, "personas") );
        wordsList.add( new Word(173, "grupo") );
        wordsList.add( new Word(174, "cuenta") );
        wordsList.add( new Word(175, "pueden") );
        wordsList.add( new Word(176, "tienen") );
        wordsList.add( new Word(177, "misma") );
        wordsList.add( new Word(178, "nueva") );
        wordsList.add( new Word(179, "cual") );
        wordsList.add( new Word(180, "fueron") );
        wordsList.add( new Word(181, "mujer") );
        wordsList.add( new Word(182, "frente") );
        wordsList.add( new Word(183, "josé") );
        wordsList.add( new Word(184, "tras") );
        wordsList.add( new Word(185, "cosas") );
        wordsList.add( new Word(186, "fin") );
        wordsList.add( new Word(187, "ciudad") );
        wordsList.add( new Word(188, "he") );
        wordsList.add( new Word(189, "social") );
        wordsList.add( new Word(190, "manera") );
        wordsList.add( new Word(191, "tener") );
        wordsList.add( new Word(192, "sistema") );
        wordsList.add( new Word(193, "será") );
        wordsList.add( new Word(194, "historia") );
        wordsList.add( new Word(195, "muchos") );
        wordsList.add( new Word(196, "juan") );
        wordsList.add( new Word(197, "tipo") );
        wordsList.add( new Word(198, "cuatro") );
        wordsList.add( new Word(199, "dentro") );
        wordsList.add( new Word(200, "nuestro") );
        wordsList.add( new Word(201, "punto") );
        wordsList.add( new Word(202, "dice") );
        wordsList.add( new Word(203, "ello") );
        wordsList.add( new Word(204, "cualquier") );
        wordsList.add( new Word(205, "noche") );
        wordsList.add( new Word(206, "aún") );
        wordsList.add( new Word(207, "agua") );
        wordsList.add( new Word(208, "parece") );
        wordsList.add( new Word(209, "haber") );
        wordsList.add( new Word(210, "situación") );
        wordsList.add( new Word(211, "fuera") );
        wordsList.add( new Word(212, "bajo") );
        wordsList.add( new Word(213, "grandes") );
        wordsList.add( new Word(214, "nuestra") );
        wordsList.add( new Word(215, "ejemplo") );
        wordsList.add( new Word(216, "acuerdo") );
        wordsList.add( new Word(217, "habían") );
        wordsList.add( new Word(218, "usted") );
        wordsList.add( new Word(219, "estados") );
        wordsList.add( new Word(220, "hizo") );
        wordsList.add( new Word(221, "nadie") );
        wordsList.add( new Word(222, "países") );
        wordsList.add( new Word(223, "horas") );
        wordsList.add( new Word(224, "posible") );
        wordsList.add( new Word(225, "tarde") );
        wordsList.add( new Word(226, "ley") );
        wordsList.add( new Word(227, "importante") );
        wordsList.add( new Word(228, "guerra") );
        wordsList.add( new Word(229, "desarrollo") );
        wordsList.add( new Word(230, "proceso") );
        wordsList.add( new Word(231, "realidad") );
        wordsList.add( new Word(232, "sentido") );
        wordsList.add( new Word(233, "lado") );
        wordsList.add( new Word(234, "mí") );
        wordsList.add( new Word(235, "tu") );
        wordsList.add( new Word(236, "cambio") );
        wordsList.add( new Word(237, "allí") );
        wordsList.add( new Word(238, "mano") );
        wordsList.add( new Word(239, "eran") );
        wordsList.add( new Word(240, "estar") );
        wordsList.add( new Word(241, "san") );
        wordsList.add( new Word(242, "número") );
        wordsList.add( new Word(243, "sociedad") );
        wordsList.add( new Word(244, "unas") );
        wordsList.add( new Word(245, "centro") );
        wordsList.add( new Word(246, "padre") );
        wordsList.add( new Word(247, "gente") );
        wordsList.add( new Word(248, "final") );
        wordsList.add( new Word(249, "relación") );
        wordsList.add( new Word(250, "cuerpo") );
        wordsList.add( new Word(251, "obra") );
        wordsList.add( new Word(252, "incluso") );
        wordsList.add( new Word(253, "través") );
        wordsList.add( new Word(254, "último") );
        wordsList.add( new Word(255, "madre") );
        wordsList.add( new Word(256, "mis") );
        wordsList.add( new Word(257, "modo") );
        wordsList.add( new Word(258, "problemas") );
        wordsList.add( new Word(259, "cinco") );
        wordsList.add( new Word(260, "carlos") );
        wordsList.add( new Word(261, "hombres") );
        wordsList.add( new Word(262, "información") );
        wordsList.add( new Word(263, "ojos") );
        wordsList.add( new Word(264, "muerte") );
        wordsList.add( new Word(265, "nombre") );
        wordsList.add( new Word(266, "algunas") );
        wordsList.add( new Word(267, "público") );
        wordsList.add( new Word(268, "mujeres") );
        wordsList.add( new Word(269, "siglo") );
        wordsList.add( new Word(270, "todavía") );
        wordsList.add( new Word(271, "meses") );
        wordsList.add( new Word(272, "mañana") );
        wordsList.add( new Word(273, "esos") );
        wordsList.add( new Word(274, "nosotros") );
        wordsList.add( new Word(275, "hora") );
        wordsList.add( new Word(276, "muchas") );
        wordsList.add( new Word(277, "pueblo") );
        wordsList.add( new Word(278, "alguna") );
        wordsList.add( new Word(279, "dar") );
        wordsList.add( new Word(280, "problema") );
        wordsList.add( new Word(281, "don") );
        wordsList.add( new Word(282, "da") );
        wordsList.add( new Word(283, "tú") );
        wordsList.add( new Word(284, "derecho") );
        wordsList.add( new Word(285, "verdad") );
        wordsList.add( new Word(286, "maría") );
        wordsList.add( new Word(287, "unidos") );
        wordsList.add( new Word(288, "podría") );
        wordsList.add( new Word(289, "sería") );
        wordsList.add( new Word(290, "junto") );
        wordsList.add( new Word(291, "cabeza") );
        wordsList.add( new Word(292, "aquel") );
        wordsList.add( new Word(293, "luis") );
        wordsList.add( new Word(294, "cuanto") );
        wordsList.add( new Word(295, "tierra") );
        wordsList.add( new Word(296, "equipo") );
        wordsList.add( new Word(297, "segundo") );
        wordsList.add( new Word(298, "director") );
        wordsList.add( new Word(299, "dicho") );
        wordsList.add( new Word(300, "cierto") );
        wordsList.add( new Word(301, "casos") );
        wordsList.add( new Word(302, "manos") );
        wordsList.add( new Word(303, "nivel") );
        wordsList.add( new Word(304, "podía") );
        wordsList.add( new Word(305, "familia") );
        wordsList.add( new Word(306, "largo") );
        wordsList.add( new Word(307, "partir") );
        wordsList.add( new Word(308, "falta") );
        wordsList.add( new Word(309, "llegar") );
        wordsList.add( new Word(310, "propio") );
        wordsList.add( new Word(311, "ministro") );
        wordsList.add( new Word(312, "cosa") );
        wordsList.add( new Word(313, "primero") );
        wordsList.add( new Word(314, "seguridad") );
        wordsList.add( new Word(315, "hemos") );
        wordsList.add( new Word(316, "mal") );
        wordsList.add( new Word(317, "trata") );
        wordsList.add( new Word(318, "algún") );
        wordsList.add( new Word(319, "tuvo") );
        wordsList.add( new Word(320, "respecto") );
        wordsList.add( new Word(321, "semana") );
        wordsList.add( new Word(322, "varios") );
        wordsList.add( new Word(323, "real") );
        wordsList.add( new Word(324, "sé") );
        wordsList.add( new Word(325, "voz") );
        wordsList.add( new Word(326, "paso") );
        wordsList.add( new Word(327, "señor") );
        wordsList.add( new Word(328, "mil") );
        wordsList.add( new Word(329, "quienes") );
        wordsList.add( new Word(330, "proyecto") );
        wordsList.add( new Word(331, "mercado") );
        wordsList.add( new Word(332, "mayoría") );
        wordsList.add( new Word(333, "luz") );
        wordsList.add( new Word(334, "claro") );
        wordsList.add( new Word(335, "iba") );
        wordsList.add( new Word(336, "éste") );
        wordsList.add( new Word(337, "pesetas") );
        wordsList.add( new Word(338, "orden") );
        wordsList.add( new Word(339, "español") );
        wordsList.add( new Word(340, "buena") );
        wordsList.add( new Word(341, "quiere") );
        wordsList.add( new Word(342, "aquella") );
        wordsList.add( new Word(343, "programa") );
        wordsList.add( new Word(344, "palabras") );
        wordsList.add( new Word(345, "internacional") );
        wordsList.add( new Word(346, "van") );
        wordsList.add( new Word(347, "esas") );
        wordsList.add( new Word(348, "segunda") );
        wordsList.add( new Word(349, "empresa") );
        wordsList.add( new Word(350, "puesto") );
        wordsList.add( new Word(351, "ahí") );
        wordsList.add( new Word(352, "propia") );
        wordsList.add( new Word(353, "m") );
        wordsList.add( new Word(354, "libro") );
        wordsList.add( new Word(355, "igual") );
        wordsList.add( new Word(356, "político") );
        wordsList.add( new Word(357, "persona") );
        wordsList.add( new Word(358, "últimos") );
        wordsList.add( new Word(359, "ellas") );
        wordsList.add( new Word(360, "total") );
        wordsList.add( new Word(361, "creo") );
        wordsList.add( new Word(362, "tengo") );
        wordsList.add( new Word(363, "dios") );
        wordsList.add( new Word(364, "") );
        wordsList.add( new Word(365, "española") );
        wordsList.add( new Word(366, "condiciones") );
        wordsList.add( new Word(367, "méxico") );
        wordsList.add( new Word(368, "fuerza") );
        wordsList.add( new Word(369, "solo") );
        wordsList.add( new Word(370, "único") );
        wordsList.add( new Word(371, "acción") );
        wordsList.add( new Word(372, "amor") );
        wordsList.add( new Word(373, "policía") );
        wordsList.add( new Word(374, "puerta") );
        wordsList.add( new Word(375, "pesar") );
        wordsList.add( new Word(376, "zona") );
        wordsList.add( new Word(377, "sabe") );
        wordsList.add( new Word(378, "calle") );
        wordsList.add( new Word(379, "interior") );
        wordsList.add( new Word(380, "tampoco") );
        wordsList.add( new Word(381, "música") );
        wordsList.add( new Word(382, "ningún") );
        wordsList.add( new Word(383, "vista") );
        wordsList.add( new Word(384, "campo") );
        wordsList.add( new Word(385, "buen") );
        wordsList.add( new Word(386, "hubiera") );
        wordsList.add( new Word(387, "saber") );
        wordsList.add( new Word(388, "obras") );
        wordsList.add( new Word(389, "razón") );
        wordsList.add( new Word(390, "ex") );
        wordsList.add( new Word(391, "niños") );
        wordsList.add( new Word(392, "presencia") );
        wordsList.add( new Word(393, "tema") );
        wordsList.add( new Word(394, "dinero") );
        wordsList.add( new Word(395, "comisión") );
        wordsList.add( new Word(396, "antonio") );
        wordsList.add( new Word(397, "servicio") );
        wordsList.add( new Word(398, "hijo") );
        wordsList.add( new Word(399, "última") );
        wordsList.add( new Word(400, "ciento") );
        wordsList.add( new Word(401, "estoy") );
        wordsList.add( new Word(402, "hablar") );
        wordsList.add( new Word(403, "dio") );
        wordsList.add( new Word(404, "minutos") );
        wordsList.add( new Word(405, "producción") );
        wordsList.add( new Word(406, "camino") );
        wordsList.add( new Word(407, "seis") );
        wordsList.add( new Word(408, "quién") );
        wordsList.add( new Word(409, "fondo") );
        wordsList.add( new Word(410, "dirección") );
        wordsList.add( new Word(411, "papel") );
        wordsList.add( new Word(412, "demás") );
        wordsList.add( new Word(413, "barcelona") );
        wordsList.add( new Word(414, "idea") );
        wordsList.add( new Word(415, "especial") );
        wordsList.add( new Word(416, "diferentes") );
        wordsList.add( new Word(417, "dado") );
        wordsList.add( new Word(418, "base") );
        wordsList.add( new Word(419, "capital") );
        wordsList.add( new Word(420, "ambos") );
        wordsList.add( new Word(421, "europa") );
        wordsList.add( new Word(422, "libertad") );
        wordsList.add( new Word(423, "relaciones") );
        wordsList.add( new Word(424, "espacio") );
        wordsList.add( new Word(425, "medios") );
        wordsList.add( new Word(426, "ir") );
        wordsList.add( new Word(427, "actual") );
        wordsList.add( new Word(428, "población") );
        wordsList.add( new Word(429, "empresas") );
        wordsList.add( new Word(430, "estudio") );
        wordsList.add( new Word(431, "salud") );
        wordsList.add( new Word(432, "servicios") );
        wordsList.add( new Word(433, "haya") );
        wordsList.add( new Word(434, "principio") );
        wordsList.add( new Word(435, "siendo") );
        wordsList.add( new Word(436, "cultura") );
        wordsList.add( new Word(437, "anterior") );
        wordsList.add( new Word(438, "alto") );
        wordsList.add( new Word(439, "media") );
        wordsList.add( new Word(440, "mediante") );
        wordsList.add( new Word(441, "primeros") );
        wordsList.add( new Word(442, "arte") );
        wordsList.add( new Word(443, "paz") );
        wordsList.add( new Word(444, "sector") );
        wordsList.add( new Word(445, "imagen") );
        wordsList.add( new Word(446, "medida") );
        wordsList.add( new Word(447, "deben") );
        wordsList.add( new Word(448, "datos") );
        wordsList.add( new Word(449, "consejo") );
        wordsList.add( new Word(450, "personal") );
        wordsList.add( new Word(451, "interés") );
        wordsList.add( new Word(452, "julio") );
        wordsList.add( new Word(453, "grupos") );
        wordsList.add( new Word(454, "miembros") );
        wordsList.add( new Word(455, "ninguna") );
        wordsList.add( new Word(456, "existe") );
        wordsList.add( new Word(457, "cara") );
        wordsList.add( new Word(458, "edad") );
        wordsList.add( new Word(459, "etc") );
        wordsList.add( new Word(460, "movimiento") );
        wordsList.add( new Word(461, "visto") );
        wordsList.add( new Word(462, "llegó") );
        wordsList.add( new Word(463, "puntos") );
        wordsList.add( new Word(464, "actividad") );
        wordsList.add( new Word(465, "bueno") );
        wordsList.add( new Word(466, "uso") );
        wordsList.add( new Word(467, "niño") );
        wordsList.add( new Word(468, "difícil") );
        wordsList.add( new Word(469, "joven") );
        wordsList.add( new Word(470, "futuro") );
        wordsList.add( new Word(471, "aquellos") );
        wordsList.add( new Word(472, "mes") );
        wordsList.add( new Word(473, "pronto") );
        wordsList.add( new Word(474, "soy") );
        wordsList.add( new Word(475, "hacía") );
        wordsList.add( new Word(476, "nuevos") );
        wordsList.add( new Word(477, "nuestros") );
        wordsList.add( new Word(478, "estaban") );
        wordsList.add( new Word(479, "posibilidad") );
        wordsList.add( new Word(480, "sigue") );
        wordsList.add( new Word(481, "cerca") );
        wordsList.add( new Word(482, "resultados") );
        wordsList.add( new Word(483, "educación") );
        wordsList.add( new Word(484, "atención") );
        wordsList.add( new Word(485, "gonzález") );
        wordsList.add( new Word(486, "capacidad") );
        wordsList.add( new Word(487, "efecto") );
        wordsList.add( new Word(488, "necesario") );
        wordsList.add( new Word(489, "valor") );
        wordsList.add( new Word(490, "aire") );
        wordsList.add( new Word(491, "investigación") );
        wordsList.add( new Word(492, "siguiente") );
        wordsList.add( new Word(493, "figura") );
        wordsList.add( new Word(494, "central") );
        wordsList.add( new Word(495, "comunidad") );
        wordsList.add( new Word(496, "necesidad") );
        wordsList.add( new Word(497, "serie") );
        wordsList.add( new Word(498, "organización") );
        wordsList.add( new Word(499, "nuevas") );
        wordsList.add( new Word(500, "calidad") );
        return wordsList;
    }

    public ArrayList<Word> readPhrasesRandom(int length) {
        ArrayList<Word> wordsList = readAllPhrases();
        ArrayList<Word> shortWordsList = new ArrayList<Word>();
        for(int i = 0; i < length; i++) {
            int randomNum = 1 + (int) (Math.random() * wordsList.size());
            shortWordsList.add( wordsList.get(randomNum) );
        }
        return shortWordsList;
    }

    public ArrayList<Word> readAllPhrases() {
        ArrayList phrasesList = new ArrayList<Word>();
        phrasesList.add(new Word(1, "A buen entendedor, pocas palabras bastan"));
        phrasesList.add(new Word(99, "A buenas horas mangas verdes "));
        phrasesList.add(new Word(99, "A bulto"));
        phrasesList.add(new Word(99, "A caballo regalado, no le mires el dentado"));
        phrasesList.add(new Word(99, "A Dios rogando y con el mazo dando"));
        phrasesList.add(new Word(99, "A falta de pan buenas son tortas"));
        phrasesList.add(new Word(99, "A fin de cuentas"));
        phrasesList.add(new Word(99, "A hangover"));
        phrasesList.add(new Word(99, "A la buena de Dios"));
        phrasesList.add(new Word(99, "A la fuerza ahorcan"));
        phrasesList.add(new Word(99, "A la vuelta de la esquina"));
        phrasesList.add(new Word(99, "A lo hecho, pecho"));
        phrasesList.add(new Word(99, "A mal tiempo, buena cara"));
        phrasesList.add(new Word(99, "A menos bulto, más claridad"));
        phrasesList.add(new Word(99, "A ojo de buen cubero"));
        phrasesList.add(new Word(99, "A otra cosa, mariposa"));
        phrasesList.add(new Word(99, "A otro perro con ese hueso"));
        phrasesList.add(new Word(99, "A palabras necias, oídos sordos"));
        phrasesList.add(new Word(99, "A palo seco"));
        phrasesList.add(new Word(99, "A perro flaco, todo son pulgas"));
        phrasesList.add(new Word(99, "A propósito"));
        phrasesList.add(new Word(99, "A quid"));
        phrasesList.add(new Word(99, "A quien a buen árbol se arrima, buena sombra le cobija"));
        phrasesList.add(new Word(99, "A quien madruga Dios le ayuda"));
        phrasesList.add(new Word(99, "A rey muerto, rey puesto"));
        phrasesList.add(new Word(99, "A todo cerdo le llega su San Martín"));
        phrasesList.add(new Word(99, "A vivir que son dos días"));
        phrasesList.add(new Word(99, "A wet blanket"));
        phrasesList.add(new Word(99, "Adonde fueres haz lo que vieres"));
        phrasesList.add(new Word(99, "Agua que no has de beber déjala correr"));
        phrasesList.add(new Word(99, "Ahogarse en un vaso de agua"));
        phrasesList.add(new Word(99, "Ahuecar el ala"));
        phrasesList.add(new Word(99, "Al pan, pan y al vino, vino"));
        phrasesList.add(new Word(99, "Al tun tun"));
        phrasesList.add(new Word(99, "Alguien que es más fácil saltarlo que darle la vuelta"));
        phrasesList.add(new Word(99, "Anda ya!"));
        phrasesList.add(new Word(99, "Anímate!"));
        phrasesList.add(new Word(99, "Arrimar el hombro"));
        phrasesList.add(new Word(99, "Arrojar perlas a los cerdos"));
        phrasesList.add(new Word(99, "Aunque la mona se vista de seda, mona se queda"));
        phrasesList.add(new Word(99, "Bajar la guardia"));
        phrasesList.add(new Word(99, "Better late than never"));
        phrasesList.add(new Word(99, "Bless you!"));
        phrasesList.add(new Word(99, "Bon apetit."));
        phrasesList.add(new Word(99, "Borracho"));
        phrasesList.add(new Word(99, "Borracho como una cuba"));
        phrasesList.add(new Word(99, "Cada maestrillo tiene su librillo"));
        phrasesList.add(new Word(99, "Cada mochuelo a su olivo"));
        phrasesList.add(new Word(99, "Caer en saco roto"));
        phrasesList.add(new Word(99, "Cálmate!"));
        phrasesList.add(new Word(99, "Cambiar de chaqueta"));
        phrasesList.add(new Word(99, "Cantar las cuarenta"));
        phrasesList.add(new Word(99, "Cargar con el mochuelo"));
        phrasesList.add(new Word(99, "Carpe Diem!"));
        phrasesList.add(new Word(99, "Cenceño"));
        phrasesList.add(new Word(99, "Cierra la puerta"));
        phrasesList.add(new Word(99, "Cojonudo"));
        phrasesList.add(new Word(99, "Como agua de mayo"));
        phrasesList.add(new Word(99, "¿Cómo es eso? ¿Por qué?"));
        phrasesList.add(new Word(99, "Como Pedro por su casa"));
        phrasesList.add(new Word(99, "Como un libro abierto"));
        phrasesList.add(new Word(99, "Con la iglesia hemos topado"));
        phrasesList.add(new Word(99, "Con la miel en los labios"));
        phrasesList.add(new Word(99, "Corpulento"));
        phrasesList.add(new Word(99, "Coser y cantar"));
        phrasesList.add(new Word(99, "Costar un huevo"));
        phrasesList.add(new Word(99, "Costar un ojo de la cara"));
        phrasesList.add(new Word(99, "Costar un riñón"));
        phrasesList.add(new Word(99, "Cría fama y échate a dormir"));
        phrasesList.add(new Word(99, "Cross your fingers"));
        phrasesList.add(new Word(99, "Cruzar los dedos"));
        phrasesList.add(new Word(99, "Cuando a uno le quedan 2 telediarios"));
        phrasesList.add(new Word(99, "Cuando algo es otro cantar"));
        phrasesList.add(new Word(99, "Cuando algo o alguien es la bomba"));
        phrasesList.add(new Word(99, "Cuando seas padre, comerás huevo"));
        phrasesList.add(new Word(99, "Dar en el clavo"));
        phrasesList.add(new Word(99, "Date prisa!"));
        phrasesList.add(new Word(99, "De bien nacidos es ser agradecidos"));
        phrasesList.add(new Word(99, "De cara a la galería"));
        phrasesList.add(new Word(99, "De nada (después de decir gracias)"));
        phrasesList.add(new Word(99, "De pocas carnes"));
        phrasesList.add(new Word(99, "De tal palo tal astilla"));
        phrasesList.add(new Word(99, "De verdad!"));
        phrasesList.add(new Word(99, "Déjame en paz"));
        phrasesList.add(new Word(99, "Delgaducho"));
        phrasesList.add(new Word(99, "Descojonarse"));
        phrasesList.add(new Word(99, "Diálogo de besugos"));
        phrasesList.add(new Word(99, "Dime cuánto (para comida o bebidas)"));
        phrasesList.add(new Word(99, "Dios los cría y ellos se juntan"));
        phrasesList.add(new Word(99, "Dorar la píldora"));
        phrasesList.add(new Word(99, "Dormir como un ceporro"));
        phrasesList.add(new Word(99, "Dormir la mona"));
        phrasesList.add(new Word(99, "Dormirse en los laureles"));
        phrasesList.add(new Word(99, "Echar leña al fuego"));
        phrasesList.add(new Word(99, "Echar margaritas a los cerdos"));
        phrasesList.add(new Word(99, "El fútbol es así"));
        phrasesList.add(new Word(99, "El hábito no hace al monje"));
        phrasesList.add(new Word(99, "El horno no está para bollos"));
        phrasesList.add(new Word(99, "El mismo perro con distinto collar"));
        phrasesList.add(new Word(99, "El mundo es un pañuelo"));
        phrasesList.add(new Word(99, "El que algo quiere, algo le cuesta"));
        phrasesList.add(new Word(99, "El que espera, desespera"));
        phrasesList.add(new Word(99, "El que la sigue la consigue"));
        phrasesList.add(new Word(99, "El que mucho abarca poco aprieta"));
        phrasesList.add(new Word(99, "El que quiera peces que se moje el culo"));
        phrasesList.add(new Word(99, "El quinto pino"));
        phrasesList.add(new Word(99, "El talón de Aquiles"));
        phrasesList.add(new Word(99, "El uno por el otro la casa sin barrer"));
        phrasesList.add(new Word(99, "En boca cerrada no entran moscas"));
        phrasesList.add(new Word(99, "En casa de herrero, cuchillo de palo"));
        phrasesList.add(new Word(99, "En el reino de los ciegos, el tuerto es el rey"));
        phrasesList.add(new Word(99, "En mi opinión"));
        phrasesList.add(new Word(99, "En peores garitas hemos hecho guardia"));
        phrasesList.add(new Word(99, "En todas partes cuecen habas"));
        phrasesList.add(new Word(99, "Enjuto"));
        phrasesList.add(new Word(99, "Entre ceja y ceja"));
        phrasesList.add(new Word(99, "Entre pitos y flautas"));
        phrasesList.add(new Word(99, "Éramos pocos y parió la abuela"));
        phrasesList.add(new Word(99, "Es peor el remedio que la enfermedad"));
        phrasesList.add(new Word(99, "Estar en la gloria"));
        phrasesList.add(new Word(99, "Escuálido"));
        phrasesList.add(new Word(99, "Escurrir el bulto"));
        phrasesList.add(new Word(99, "Estar acojonado"));
        phrasesList.add(new Word(99, "Estar borracho"));
        phrasesList.add(new Word(99, "Estar cascado"));
        phrasesList.add(new Word(99, "Estar cogido con alfileres"));
        phrasesList.add(new Word(99, "Estar cogido con pinzas"));
        phrasesList.add(new Word(99, "Estar como el quico"));
        phrasesList.add(new Word(99, "Estar como pez en el agua"));
        phrasesList.add(new Word(99, "Estar como una cuba"));
        phrasesList.add(new Word(99, "Estar de buen año"));
        phrasesList.add(new Word(99, "Estar de buen ver"));
        phrasesList.add(new Word(99, "Estar de miranda"));
        phrasesList.add(new Word(99, "Estar entrado en carnes"));
        phrasesList.add(new Word(99, "Estar entre los brazos de Morfeo"));
        phrasesList.add(new Word(99, "Estar espeso"));
        phrasesList.add(new Word(99, "Estar flaco"));
        phrasesList.add(new Word(99, "Estar hasta los cojones"));
        phrasesList.add(new Word(99, "Estar hecho un cristo"));
        phrasesList.add(new Word(99, "Estar hecho un flan"));
        phrasesList.add(new Word(99, "Estar hecho un trapo"));
        phrasesList.add(new Word(99, "Estar hermoso"));
        phrasesList.add(new Word(99, "Estar para mojar pan"));
        phrasesList.add(new Word(99, "Estar patas arriba"));
        phrasesList.add(new Word(99, "Estar piripi"));
        phrasesList.add(new Word(99, "Estar rollizo"));
        phrasesList.add(new Word(99, "Estar siempre con la misma canción"));
        phrasesList.add(new Word(99, "Estar tan delgado que llueve y no te mojas"));
        phrasesList.add(new Word(99, "Estar zamproño"));
        phrasesList.add(new Word(99, "Estás de broma"));
        phrasesList.add(new Word(99, "Esto es Jauja"));
        phrasesList.add(new Word(99, "Faltar un tornillo"));
        phrasesList.add(new Word(99, "Ha pasado un ángel"));
        phrasesList.add(new Word(99, "Haber pillado un buen pedal"));
        phrasesList.add(new Word(99, "Hablando del rey de Roma"));
        phrasesList.add(new Word(99, "Hablando del rey de Roma, por la puerta asoma"));
        phrasesList.add(new Word(99, "Hablar por los codos"));
        phrasesList.add(new Word(99, "Hacer algo a troche y moche"));
        phrasesList.add(new Word(99, "Hacer borrón y cuenta nueva"));
        phrasesList.add(new Word(99, "Hacer buenas migas"));
        phrasesList.add(new Word(99, "Hacer bulto"));
        phrasesList.add(new Word(99, "Hacer el mono"));
        phrasesList.add(new Word(99, "Hacer la cabra"));
        phrasesList.add(new Word(99, "Hacer la pelota"));
        phrasesList.add(new Word(99, "Hacer la visita del médico"));
        phrasesList.add(new Word(99, "Hacer leña del árbol caído"));
        phrasesList.add(new Word(99, "Hacerse el sueco"));
        phrasesList.add(new Word(99, "Hacerse el sueco"));
        phrasesList.add(new Word(99, "Hacerse la boca agua"));
        phrasesList.add(new Word(99, "Hacía un frío de cojones"));
        phrasesList.add(new Word(99, "Hasta el rabo todo es toro"));
        phrasesList.add(new Word(99, "Hondonadas de hostias"));
        phrasesList.add(new Word(99, "Hostia"));
        phrasesList.add(new Word(99, "Hoy por ti mañana por mí"));
        phrasesList.add(new Word(99, "Ir a toda hostia"));
        phrasesList.add(new Word(99, "Ir al grano"));
        phrasesList.add(new Word(99, "Ir bien cocido"));
        phrasesList.add(new Word(99, "Ir bolinga"));
        phrasesList.add(new Word(99, "Ir ciego"));
        phrasesList.add(new Word(99, "Ir con pies de plomo"));
        phrasesList.add(new Word(99, "Ir ebrio"));
        phrasesList.add(new Word(99, "Ir hecho un Ecce Homo"));
        phrasesList.add(new Word(99, "Ir mamado"));
        phrasesList.add(new Word(99, "Ir pisando huevos"));
        phrasesList.add(new Word(99, "Irse bebiendo hasta el agua de los floreros"));
        phrasesList.add(new Word(99, "Irse con la música a otra parte"));
        phrasesList.add(new Word(99, "Irse por los cerros de Úbeda"));
        phrasesList.add(new Word(99, "Jesús! (cuando alguien estornuda)"));
        phrasesList.add(new Word(99, "La avaricia rompe el saco"));
        phrasesList.add(new Word(99, "La cabra siempre tira al monte"));
        phrasesList.add(new Word(99, "La esperanza es lo último que se pierde"));
        phrasesList.add(new Word(99, "La gota que colmó el vaso"));
        phrasesList.add(new Word(99, "La media naranja"));
        phrasesList.add(new Word(99, "La pescadilla que se muerde la cola"));
        phrasesList.add(new Word(99, "Lágrimas de cocodrilo"));
        phrasesList.add(new Word(99, "Le costó mil pares de huevos"));
        phrasesList.add(new Word(99, "Le ha salido el tiro por la culata"));
        phrasesList.add(new Word(99, "Leave me alone"));
        phrasesList.add(new Word(99, "Let the cat out of the bag"));
        phrasesList.add(new Word(99, "Let’s have one for the road"));
        phrasesList.add(new Word(99, "Liarse la manta a la cabeza"));
        phrasesList.add(new Word(99, "Ligar con alguien"));
        phrasesList.add(new Word(99, "Llegar y besar el santo"));
        phrasesList.add(new Word(99, "Llevar la voz cantante"));
        phrasesList.add(new Word(99, "Llevar los pantalones"));
        phrasesList.add(new Word(99, "Llevar un buen melocotón"));
        phrasesList.add(new Word(99, "Llevar un buen pedo o ir pedo perdido"));
        phrasesList.add(new Word(99, "Llevar un buen puntazo"));
        phrasesList.add(new Word(99, "Llevar una buena cogorza"));
        phrasesList.add(new Word(99, "Llevar una buena melopea"));
        phrasesList.add(new Word(99, "Llevar una buena mierda encima"));
        phrasesList.add(new Word(99, "Llevarse como el perro y el gato"));
        phrasesList.add(new Word(99, "Llevarse el gato al agua"));
        phrasesList.add(new Word(99, "Llover a mares o llover a cántaros"));
        phrasesList.add(new Word(99, "Llueve sobre mojado"));
        phrasesList.add(new Word(99, "Lo haré por cojones"));
        phrasesList.add(new Word(99, "Lo mereces"));
        phrasesList.add(new Word(99, "Los huevos, ingrediente indispensable de muchas expresiones españolas"));
        phrasesList.add(new Word(99, "Magro"));
        phrasesList.add(new Word(99, "Mal de muchos, consuelo de tontos"));
        phrasesList.add(new Word(99, "Mala hierba nunca muere"));
        phrasesList.add(new Word(99, "Manga por Hombro"));
        phrasesList.add(new Word(99, "Más claro que el agua"));
        phrasesList.add(new Word(99, "Más vale pájaro en mano que ciento volando"));
        phrasesList.add(new Word(99, "Más vale tarde que nunca"));
        phrasesList.add(new Word(99, "Más vale tarde que nunca"));
        phrasesList.add(new Word(99, "Más vale tarde que nunca"));
        phrasesList.add(new Word(99, "Matar dos pájaros de un tiro"));
        phrasesList.add(new Word(99, "Matar el gusanillo"));
        phrasesList.add(new Word(99, "Matar moscas a cañonazos"));
        phrasesList.add(new Word(99, "Me estás tomando el pelo"));
        phrasesList.add(new Word(99, "Me ha salido rana"));
        phrasesList.add(new Word(99, "Me importa 3 huevos"));
        phrasesList.add(new Word(99, "Me sabe mal"));
        phrasesList.add(new Word(99, "Me salió de cojones"));
        phrasesList.add(new Word(99, "Me suena"));
        phrasesList.add(new Word(99, "Me toca los huevos"));
        phrasesList.add(new Word(99, "Meter el dedo en la llaga"));
        phrasesList.add(new Word(99, "Meter cizaña"));
        phrasesList.add(new Word(99, "Meter la pata"));
        phrasesList.add(new Word(99, "Miel sobre hojuelas"));
        phrasesList.add(new Word(99, "Mojar"));
        phrasesList.add(new Word(99, "Mojar a alguien"));
        phrasesList.add(new Word(99, "Mojar la cama"));
        phrasesList.add(new Word(99, "Mojar la camiseta"));
        phrasesList.add(new Word(99, "Mojar un evento"));
        phrasesList.add(new Word(99, "Mojarse"));
        phrasesList.add(new Word(99, "Monto un circo y me crecen los enanos"));
        phrasesList.add(new Word(99, "Morir de éxito"));
        phrasesList.add(new Word(99, "Mucho ruido y pocas nueces"));
        phrasesList.add(new Word(99, "Muerto el perro, se acabó la rabia"));
        phrasesList.add(new Word(99, "Ni fu ni fa"));
        phrasesList.add(new Word(99, "Ni harto de vino"));
        phrasesList.add(new Word(99, "Ni me va ni me viene"));
        phrasesList.add(new Word(99, "No dar el brazo a torcer"));
        phrasesList.add(new Word(99, "No dar un palo al agua"));
        phrasesList.add(new Word(99, "No dejes para mañana lo que puedas hacer hoy"));
        phrasesList.add(new Word(99, "No es oro todo lo que reluce"));
        phrasesList.add(new Word(99, "No faltaría mas"));
        phrasesList.add(new Word(99, "No hay mal que por bien no venga"));
        phrasesList.add(new Word(99, "No hay peor ciego que el que no quiere ver"));
        phrasesList.add(new Word(99, "No me extraña"));
        phrasesList.add(new Word(99, "No pegar ojo"));
        phrasesList.add(new Word(99, "No pegar ni con cola"));
        phrasesList.add(new Word(99, "No por mucho madrugar, amanece más temprano"));
        phrasesList.add(new Word(99, "No se hizo la miel para la boca del asno"));
        phrasesList.add(new Word(99, "No se puede vender la piel del oso antes de cazarlo"));
        phrasesList.add(new Word(99, "No ser trigo limpio"));
        phrasesList.add(new Word(99, "No sólo de pan vive el hombre"));
        phrasesList.add(new Word(99, "No tener abuela"));
        phrasesList.add(new Word(99, "No tengo ni idea"));
        phrasesList.add(new Word(99, "No todo el monte es orégano"));
        phrasesList.add(new Word(99, "No wonder"));
        phrasesList.add(new Word(99, "Nos ha salido redondo"));
        phrasesList.add(new Word(99, "Nos ha tocado el gordo"));
        phrasesList.add(new Word(99, "Nunca digas de este agua no beberé"));
        phrasesList.add(new Word(99, "Obeso"));
        phrasesList.add(new Word(99, "Ojalá"));
        phrasesList.add(new Word(99, "Ojos que no ven, corazón que no siente"));
        phrasesList.add(new Word(99, "Olerse la tostada"));
        phrasesList.add(new Word(99, "Otro gallo cantaría"));
        phrasesList.add(new Word(99, "Pagar en efectivo"));
        phrasesList.add(new Word(99, "Pan para hoy y hambre para mañana"));
        phrasesList.add(new Word(99, "Parecer un spaguetti"));
        phrasesList.add(new Word(99, "Pasar página"));
        phrasesList.add(new Word(99, "Pasar por el aro"));
        phrasesList.add(new Word(99, "Pasarse 3 pueblos"));
        phrasesList.add(new Word(99, "Pedirle peras al olmo"));
        phrasesList.add(new Word(99, "Perder el Norte"));
        phrasesList.add(new Word(99, "Perro ladrador poco mordedor"));
        phrasesList.add(new Word(99, "Pillar una tajada o ir con la tajá"));
        phrasesList.add(new Word(99, "Pingüe"));
        phrasesList.add(new Word(99, "Pintar la mona"));
        phrasesList.add(new Word(99, "Piropos"));
        phrasesList.add(new Word(99, "Poner cara de póquer"));
        phrasesList.add(new Word(99, "Poner los huevos sobre la mesa"));
        phrasesList.add(new Word(99, "Poner los puntos sobre las íes"));
        phrasesList.add(new Word(99, "Ponerse las pilas"));
        phrasesList.add(new Word(99, "Ponerse morado"));
        phrasesList.add(new Word(99, "Por H o por B"));
        phrasesList.add(new Word(99, "Por la boca muere el pez"));
        phrasesList.add(new Word(99, "Por si las moscas"));
        phrasesList.add(new Word(99, "Por supuesto"));
        phrasesList.add(new Word(99, "Porque hoy es hoy"));
        phrasesList.add(new Word(99, "Qué aproveche o Buen provecho"));
        phrasesList.add(new Word(99, "Qué cara!"));
        phrasesList.add(new Word(99, "Qué lío!"));
        phrasesList.add(new Word(99, "Que me quiten lo bailao"));
        phrasesList.add(new Word(99, "Que si quieres arroz Catalina"));
        phrasesList.add(new Word(99, "Qué timo!"));
        phrasesList.add(new Word(99, "Quedarse a cuadros"));
        phrasesList.add(new Word(99, "Quedarse con la copla"));
        phrasesList.add(new Word(99, "Quedarse en el tintero"));
        phrasesList.add(new Word(99, "Quedarse frito"));
        phrasesList.add(new Word(99, "Quédate con el cambio"));
        phrasesList.add(new Word(99, "Quien evita la ocasión evita el peligro"));
        phrasesList.add(new Word(99, "Quien siembra vientos recoge tempestades"));
        phrasesList.add(new Word(99, "Rascarse la barriga"));
        phrasesList.add(new Word(99, "Really!"));
        phrasesList.add(new Word(99, "Revelar un secreto"));
        phrasesList.add(new Word(99, "Reza, pero sigue remando"));
        phrasesList.add(new Word(99, "Rizar el rizo"));
        phrasesList.add(new Word(99, "Romper el hielo"));
        phrasesList.add(new Word(99, "Saber a gloria"));
        phrasesList.add(new Word(99, "Sacar las castañas del fuego"));
        phrasesList.add(new Word(99, "Salir del armario"));
        phrasesList.add(new Word(99, "Salirse de madre"));
        phrasesList.add(new Word(99, "Salud!"));
        phrasesList.add(new Word(99, "Salvarse por los pelos"));
        phrasesList.add(new Word(99, "Same here"));
        phrasesList.add(new Word(99, "Sarna con gusto no pica"));
        phrasesList.add(new Word(99, "Say when"));
        phrasesList.add(new Word(99, "Se le va la olla a alguien"));
        phrasesList.add(new Word(99, "Se me ha ido el santo al cielo"));
        phrasesList.add(new Word(99, "Seboso"));
        phrasesList.add(new Word(99, "Seco"));
        phrasesList.add(new Word(99, "Ser alguien de abultadas carnes"));
        phrasesList.add(new Word(99, "Ser alguien inmenso"));
        phrasesList.add(new Word(99, "Ser como el perro del hortelano, que ni come ni deja comer"));
        phrasesList.add(new Word(99, "Ser como un libro abierto"));
        phrasesList.add(new Word(99, "Ser de la cofradía del puño"));
        phrasesList.add(new Word(99, "Ser de la virgen del puño"));
        phrasesList.add(new Word(99, "Ser de piedra"));
        phrasesList.add(new Word(99, "Ser despedido"));
        phrasesList.add(new Word(99, "Ser flor de un día"));
        phrasesList.add(new Word(99, "Ser la hostia"));
        phrasesList.add(new Word(99, "Ser la oveja negra"));
        phrasesList.add(new Word(99, "Ser más caro el collar que el perro"));
        phrasesList.add(new Word(99, "Ser más corto que las mangas de un chaleco"));
        phrasesList.add(new Word(99, "Ser más papista que el Papa"));
        phrasesList.add(new Word(99, "Ser pan comido"));
        phrasesList.add(new Word(99, "Ser todo oídos (o ser toda oídos)"));
        phrasesList.add(new Word(99, "Ser un aguafiestas"));
        phrasesList.add(new Word(99, "Ser un bala perdida"));
        phrasesList.add(new Word(99, "Ser un chaquetero"));
        phrasesList.add(new Word(99, "Ser un correveidile"));
        phrasesList.add(new Word(99, "Ser un gorrón"));
        phrasesList.add(new Word(99, "Ser un manitas"));
        phrasesList.add(new Word(99, "Ser un pedazo de pan"));
        phrasesList.add(new Word(99, "Ser un peliculero"));
        phrasesList.add(new Word(99, "Ser un pelota"));
        phrasesList.add(new Word(99, "Ser un tiquismiquis"));
        phrasesList.add(new Word(99, "Ser una monada"));
        phrasesList.add(new Word(99, "Ser uña y carne"));
        phrasesList.add(new Word(99, "Si las barbas de tu vecino ves cortar, pon las tuyas a remojar"));
        phrasesList.add(new Word(99, "Si lloras por no haber visto el Sol las lágrimas te impedirán ver las estrellas"));
        phrasesList.add(new Word(99, "Siéntete como en tu casa"));
        phrasesList.add(new Word(99, "Sin comerlo ni beberlo"));
        phrasesList.add(new Word(99, "Sírvete"));
        phrasesList.add(new Word(99, "Sobre gustos no hay nada escrito"));
        phrasesList.add(new Word(99, "Ten cuidado!"));
        phrasesList.add(new Word(99, "Tener el mono"));
        phrasesList.add(new Word(99, "Tener enchufe"));
        phrasesList.add(new Word(99, "Tener huevos"));
        phrasesList.add(new Word(99, "Tener la mosca detrás de la oreja"));
        phrasesList.add(new Word(99, "Tener la sartén por el mango"));
        phrasesList.add(new Word(99, "Tener mala hostia"));
        phrasesList.add(new Word(99, "Tener más cara que espalda"));
        phrasesList.add(new Word(99, "Tener más cuento que Calleja"));
        phrasesList.add(new Word(99, "Tener mucho morro"));
        phrasesList.add(new Word(99, "Tener muchos tiros pegaos"));
        phrasesList.add(new Word(99, "Tener pocas luces"));
        phrasesList.add(new Word(99, "Tener un as en la manga"));
        phrasesList.add(new Word(99, "Tener un morro que se lo pisa"));
        phrasesList.add(new Word(99, "Tengo que irme"));
        phrasesList.add(new Word(99, "Tiene huevos la cosa"));
        phrasesList.add(new Word(99, "Tiene un par de huevos"));
        phrasesList.add(new Word(99, "Tirar de la manta"));
        phrasesList.add(new Word(99, "Tirar la piedra y esconder la mano"));
        phrasesList.add(new Word(99, "Tirar la toalla"));
        phrasesList.add(new Word(99, "Tirar los tejos"));
        phrasesList.add(new Word(99, "Tirarse los trastos a la cabeza"));
        phrasesList.add(new Word(99, "Tocando madera"));
        phrasesList.add(new Word(99, "Tocarse los huevos"));
        phrasesList.add(new Word(99, "Tócate los huevos"));
        phrasesList.add(new Word(99, "Tomamos la penúltima"));
        phrasesList.add(new Word(99, "Tomar el pelo"));
        phrasesList.add(new Word(99, "Tropezar dos veces con la misma piedra"));
        phrasesList.add(new Word(99, "Tú eliges"));
        phrasesList.add(new Word(99, "Un aguafiestas"));
        phrasesList.add(new Word(99, "Un día es un día"));
        phrasesList.add(new Word(99, "Una libra"));
        phrasesList.add(new Word(99, "Una resaca"));
        phrasesList.add(new Word(99, "Verse a la legua"));
        phrasesList.add(new Word(99, "Y un huevo"));
        phrasesList.add(new Word(99, "Yo también"));
        phrasesList.add(new Word(99, "Zapatero a tus zapatos"));
        return phrasesList;
    }
    
}
